# Generated by Django 4.1.13 on 2024-07-14 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank='false', max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('number', models.CharField(blank='false', max_length=13, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
